param(
    [string]$RepoRoot = (Split-Path $PSScriptRoot -Parent),
    [ValidateSet('Prompt', 'Update', 'Reinstall')]
    [string]$InstalledPackageAction = 'Prompt',
    [switch]$InstallDevelopmentToolchain
)

$ErrorActionPreference = 'Stop'

function Ensure-ScoopInstalled {
    if (-not (Get-Command scoop -ErrorAction SilentlyContinue)) {
        throw 'Scoop is not installed or not available in PATH.'
    }
}
function Get-ScoopConfigPath {
    return Join-Path $HOME '.config\scoop\config.json'
}

function Get-ScoopConfigValue {
    param([Parameter(Mandatory = $true)][string]$Name)

    $configPath = Get-ScoopConfigPath
    if (-not (Test-Path -LiteralPath $configPath)) {
        return $null
    }

    $raw = Get-Content -LiteralPath $configPath -Raw
    if ([string]::IsNullOrWhiteSpace($raw)) {
        return $null
    }

    $config = $raw | ConvertFrom-Json
    return $config.$Name
}

function Install-ScoopManifestWithoutJunction {
    param([Parameter(Mandatory = $true)][string]$ManifestUrl)

    $configName = 'no_junction'
    $previousValue = Get-ScoopConfigValue -Name $configName
    $hadPreviousValue = $null -ne $previousValue

    if (-not $hadPreviousValue -or -not [bool]$previousValue) {
        scoop config $configName true | Out-Null
    }

    try {
        scoop install $ManifestUrl
    } finally {
        if (-not $hadPreviousValue) {
            scoop config rm $configName | Out-Null
        } elseif (-not [bool]$previousValue) {
            scoop config $configName $previousValue | Out-Null
        }
    }
}

function Ensure-ScoopPackage {
    param(
        [Parameter(Mandatory = $true)][string]$Name,
        [string]$Bucket,
        [string]$FallbackManifestUrl,
        [ValidateSet('Prompt', 'Update', 'Reinstall')]
        [string]$InstalledAction = 'Prompt'
    )
    $installed = scoop list | Select-String -Pattern ("(?m)^" + [regex]::Escape($Name) + "\s")
    if (-not $installed) {
        $bucketReady = $true
        if ($Bucket) {
            $bucketInstalled = scoop bucket list | Select-String -Pattern ("(?m)^" + [regex]::Escape($Bucket) + "\s")
            if (-not $bucketInstalled) {
                try {
                    scoop bucket add $Bucket
                } catch {
                    if (-not $FallbackManifestUrl) {
                        throw
                    }

                    Write-Warning "Unable to add Scoop bucket '$Bucket'. Falling back to manifest URL for '$Name'."
                    $bucketReady = $false
                }
            }
        }

        if ($bucketReady) {
            try {
                scoop install $Name
                return
            } catch {
                if (-not $FallbackManifestUrl) {
                    throw
                }

                Write-Warning "Unable to install '$Name' from Scoop bucket metadata. Falling back to manifest URL."
            }
        }

        Install-ScoopManifestWithoutJunction -ManifestUrl $FallbackManifestUrl
        return
    }

    $action = $InstalledAction
    if ($InstalledAction -eq 'Prompt') {
        $choice = Read-Host "Package '$Name' is already installed. Choose [U]pdate or [R]einstall (default: U)"
        if ($choice -match '^(r|reinstall)$') {
            $action = 'Reinstall'
        } else {
            $action = 'Update'
        }
    }

    if ($action -eq 'Reinstall') {
        scoop uninstall $Name
        try {
            scoop install $Name
        } catch {
            if (-not $FallbackManifestUrl) {
                throw
            }

            Write-Warning "Unable to reinstall '$Name' from Scoop bucket metadata. Falling back to manifest URL."
            Install-ScoopManifestWithoutJunction -ManifestUrl $FallbackManifestUrl
        }
        return
    }
    try {
        scoop update $Name
    } catch {
        if (-not $FallbackManifestUrl) {
            throw
        }

        Write-Warning "Unable to update '$Name' from Scoop bucket metadata. Reinstalling from manifest URL."
        scoop uninstall $Name
        Install-ScoopManifestWithoutJunction -ManifestUrl $FallbackManifestUrl
    }
}

function Backup-ExistingPath {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$TargetPath
    )

    if (-not (Test-Path -LiteralPath $Path)) { return }

    $item = Get-Item -LiteralPath $Path -Force
    if ($item.LinkType) {
        # Replacing a link never destroys data; the link target stays untouched
        Remove-Item -LiteralPath $Path -Force -Recurse
        return
    }

    if (-not $item.PSIsContainer) {
        # Files generated by previous runs (fallback loaders or copies) can be replaced safely
        $sameContent = (Test-Path -LiteralPath $TargetPath -PathType Leaf) -and
            ((Get-FileHash -LiteralPath $Path).Hash -eq (Get-FileHash -LiteralPath $TargetPath).Hash)
        $content = Get-Content -LiteralPath $Path -Raw -ErrorAction SilentlyContinue
        $referencesTarget = $content -and
            (($content -match [regex]::Escape($TargetPath)) -or ($content -match [regex]::Escape($TargetPath.Replace('\', '/'))))
        if ($sameContent -or $referencesTarget) {
            Remove-Item -LiteralPath $Path -Force
            return
        }
    }

    $backup = "$Path.bak.$(Get-Date -Format 'yyyyMMddHHmmss')"
    Move-Item -LiteralPath $Path -Destination $backup
    Write-Warning "Existing path moved to backup: $backup"
}

function New-DirectoryLink {
    param(
        [Parameter(Mandatory = $true)][string]$LinkPath,
        [Parameter(Mandatory = $true)][string]$TargetPath
    )

    Backup-ExistingPath $LinkPath $TargetPath
    try {
        New-Item -ItemType SymbolicLink -Path $LinkPath -Target $TargetPath | Out-Null
    } catch {
        New-Item -ItemType Junction -Path $LinkPath -Target $TargetPath | Out-Null
    }
}

function New-ProfileLink {
    param(
        [Parameter(Mandatory = $true)][string]$LinkPath,
        [Parameter(Mandatory = $true)][string]$TargetPath
    )

    Backup-ExistingPath $LinkPath $TargetPath
    try {
        New-Item -ItemType SymbolicLink -Path $LinkPath -Target $TargetPath | Out-Null
    } catch {
        $escaped = $TargetPath.Replace("'", "''")
        Set-Content -Path $LinkPath -Encoding utf8 -Value ". '$escaped'"
    }
}

function Remove-LegacyWezTermHomeConfig {
    param(
        [Parameter(Mandatory = $true)][string]$LegacyPath,
        [Parameter(Mandatory = $true)][string]$RepoWezTermDir
    )

    if (-not (Test-Path -LiteralPath $LegacyPath)) { return }

    $item = Get-Item -LiteralPath $LegacyPath -Force
    $repoEntry = Join-Path $RepoWezTermDir 'wezterm.lua'
    if ($item.LinkType) {
        $target = @($item.Target)[0]
        if ($target -and (
                [string]::Equals($target, $repoEntry, [System.StringComparison]::OrdinalIgnoreCase) -or
                [string]::Equals($target, $RepoWezTermDir, [System.StringComparison]::OrdinalIgnoreCase)
            )) {
            Remove-Item -LiteralPath $LegacyPath -Force
            Write-Host "Removed legacy WezTerm link: $LegacyPath" -ForegroundColor DarkGray
            return
        }
    }

    $content = Get-Content -LiteralPath $LegacyPath -Raw -ErrorAction SilentlyContinue
    if ($content -and (
            $content -match [regex]::Escape($repoEntry) -or
            $content -match [regex]::Escape($repoEntry.Replace('\', '/')) -or
            $content -match [regex]::Escape($RepoWezTermDir) -or
            $content -match [regex]::Escape($RepoWezTermDir.Replace('\', '/'))
        )) {
        Remove-Item -LiteralPath $LegacyPath -Force
        Write-Host "Removed legacy WezTerm loader: $LegacyPath" -ForegroundColor DarkGray
        return
    }

    $backup = "$LegacyPath.bak.$(Get-Date -Format 'yyyyMMddHHmmss')"
    Move-Item -LiteralPath $LegacyPath -Destination $backup
    Write-Warning "Legacy WezTerm home config moved to backup: $backup"
}

function New-ConfigFileLink {
    param(
        [Parameter(Mandatory = $true)][string]$LinkPath,
        [Parameter(Mandatory = $true)][string]$TargetPath
    )

    Backup-ExistingPath $LinkPath $TargetPath
    New-Item -ItemType Directory -Force -Path (Split-Path $LinkPath -Parent) | Out-Null
    try {
        New-Item -ItemType SymbolicLink -Path $LinkPath -Target $TargetPath | Out-Null
    } catch {
        Copy-Item -LiteralPath $TargetPath -Destination $LinkPath -Force
        Write-Warning "Symlink failed for '$LinkPath'; copied file instead (edits will not sync back to the repo)."
    }
}

function New-ZellijConfigLink {
    param(
        [Parameter(Mandatory = $true)][string]$LinkPath,
        [Parameter(Mandatory = $true)][string]$TargetPath
    )

    Backup-ExistingPath $LinkPath $TargetPath
    try {
        New-Item -ItemType SymbolicLink -Path $LinkPath -Target $TargetPath | Out-Null
    } catch {
        # For zellij config, copy the actual content instead of sourcing
        Copy-Item -Path $TargetPath -Destination $LinkPath -Force
    }
}

Ensure-ScoopInstalled

Write-Host 'Updating Scoop buckets...' -ForegroundColor Cyan
scoop update | Out-Null

$mainPackages = @(
    'bat',
    'bun',
    'eza',
    'fd',
    'ffmpeg',
    'fzf',
    'imagemagick',
    'jq',
    'less',
    'mingw',
    'neovim',
    'pixi',
    'poppler',
    'resvg',
    'rip',
    'ripgrep',
    'yazi',
    'uv',
    'zellij',
    'zoxide',
    '7zip'
)

# Skip Scoop pwsh if already available (e.g. MS Store version) to save disk space
if (-not (Get-Command pwsh -ErrorAction SilentlyContinue)) {
    $mainPackages += 'pwsh'
} else {
    Write-Host "pwsh already available at $((Get-Command pwsh).Source). Skipping Scoop install." -ForegroundColor DarkGray
}

# Get all installed packages at once for batch processing
$installedOutput = scoop list 2>$null
$installedSet = @{}
if ($installedOutput) {
    $installedOutput | ForEach-Object {
        if ($_ -match '^(\S+)') {
            $installedSet[$matches[1]] = $true
        }
    }
}

# Separate packages by installation status
$notInstalled = @($mainPackages | Where-Object { -not $installedSet.ContainsKey($_) })
$alreadyInstalled = @($mainPackages | Where-Object { $installedSet.ContainsKey($_) })

# Batch install uninstalled packages
if ($notInstalled.Count -gt 0) {
    Write-Host "Installing $($notInstalled.Count) packages: $($notInstalled -join ', ')" -ForegroundColor Cyan
    scoop install @notInstalled
}

# Handle already installed packages based on action
if ($alreadyInstalled.Count -gt 0) {
    if ($InstalledPackageAction -eq 'Update') {
        Write-Host "Updating $($alreadyInstalled.Count) packages" -ForegroundColor Cyan
        scoop update @alreadyInstalled
    } elseif ($InstalledPackageAction -eq 'Reinstall') {
        foreach ($pkg in $alreadyInstalled) {
            Write-Host "Reinstalling '$pkg'..." -ForegroundColor Cyan
            scoop uninstall $pkg
            scoop install $pkg
        }
    } elseif ($InstalledPackageAction -eq 'Prompt') {
        Write-Host "Already installed ($($alreadyInstalled.Count)): $($alreadyInstalled -join ', ')" -ForegroundColor DarkGray
        Write-Host 'Skipping updates. Use -InstalledPackageAction Update or Reinstall to refresh them.' -ForegroundColor Yellow
    }
}

# Handle lazygit and neovide separately (from extras bucket)
Ensure-ScoopPackage -Name 'lazygit' -Bucket 'extras' -FallbackManifestUrl 'https://raw.githubusercontent.com/ScoopInstaller/Extras/master/bucket/lazygit.json' -InstalledAction $InstalledPackageAction

# Skip Scoop neovide if already available (e.g. manually installed on another drive) to save C: space
if (Get-Command neovide -ErrorAction SilentlyContinue) {
    Write-Host "neovide already available at $((Get-Command neovide).Source). Skipping Scoop install." -ForegroundColor DarkGray
} else {
    Ensure-ScoopPackage -Name 'neovide' -Bucket 'extras' -FallbackManifestUrl 'https://raw.githubusercontent.com/ScoopInstaller/Extras/master/bucket/neovide.json' -InstalledAction $InstalledPackageAction
}

# WezTerm nightly (versions bucket). Stable extras/wezterm is stuck on 20240203.
$weztermStableDir = Join-Path $HOME 'scoop\apps\wezterm'
if (Test-Path -LiteralPath $weztermStableDir) {
    Write-Host 'Removing Scoop stable wezterm in favor of wezterm-nightly...' -ForegroundColor Cyan
    scoop uninstall wezterm
}
Ensure-ScoopPackage -Name 'wezterm-nightly' -Bucket 'versions' -FallbackManifestUrl 'https://raw.githubusercontent.com/ScoopInstaller/Versions/master/bucket/wezterm-nightly.json' -InstalledAction $InstalledPackageAction

# Uninstall Program Files WezTerm (old stable, doesn't support ~/.config/wezterm modular config)
$programFilesWez = Join-Path ${env:ProgramFiles} 'WezTerm\wezterm.exe'
if (Test-Path -LiteralPath $programFilesWez) {
    Write-Host "Uninstalling old Program Files WezTerm to avoid PATH shadowing..." -ForegroundColor Cyan
    $wezUninstaller = Get-ChildItem -Path (Join-Path ${env:ProgramFiles} 'WezTerm') -Filter 'unins*.exe' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($wezUninstaller) {
        $isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
        $args = '/SILENT /SUPPRESSMSGBOXES /NORESTART'
        try {
            if ($isAdmin) {
                Start-Process -FilePath $wezUninstaller.FullName -ArgumentList $args -Wait -NoNewWindow -ErrorAction Stop
            } else {
                Start-Process -FilePath $wezUninstaller.FullName -ArgumentList $args -Wait -Verb RunAs -ErrorAction Stop
            }
        } catch {
            Write-Warning "Could not auto-uninstall Program Files WezTerm (needs admin/UAC). Please uninstall it manually: $programFilesWez"
        }
        if (Test-Path -LiteralPath $programFilesWez) {
            Write-Warning "Program Files WezTerm still exists at $programFilesWez. Please uninstall it manually to avoid PATH shadowing."
        } else {
            Write-Host "Old WezTerm removed from Program Files." -ForegroundColor DarkGray
        }
    } else {
        Write-Warning "Program Files WezTerm found at $programFilesWez but no uninstaller located. Please uninstall it manually."
    }
}

# ---------- Fonts ----------
$fontPackages = @(
    'JetBrainsMono-NF',
    'Maple-Mono-NF-CN'
)

$nerdFontsBucket = scoop bucket list | Select-String -Pattern '(?m)^nerd-fonts\s'
if (-not $nerdFontsBucket) {
    Write-Host "Adding nerd-fonts bucket..." -ForegroundColor Cyan
    scoop bucket add nerd-fonts
}

$installedFonts = @{}
scoop list 2>$null | ForEach-Object { if ($_ -match '^(\S+)') { $installedFonts[$matches[1]] = $true } }

$fontsToInstall = $fontPackages | Where-Object { -not $installedFonts.ContainsKey($_) }
$fontsInstalled = $fontPackages | Where-Object { $installedFonts.ContainsKey($_) }

if ($fontsToInstall.Count -gt 0) {
    Write-Host "Installing fonts: $($fontsToInstall -join ', ')" -ForegroundColor Cyan
    scoop install @fontsToInstall
}
if ($fontsInstalled.Count -gt 0) {
    if ($InstalledPackageAction -eq 'Update') {
        scoop update @fontsInstalled
    } elseif ($InstalledPackageAction -eq 'Reinstall') {
        scoop uninstall @fontsInstalled
        scoop install @fontsInstalled
    } else {
        Write-Host "Fonts already installed: $($fontsInstalled -join ', ')" -ForegroundColor Yellow
    }
}

# Install Bun tools (opencode-ai, codex)
if (Get-Command bun -ErrorAction SilentlyContinue) {
    Write-Host "Installing Bun tools: opencode-ai, codex" -ForegroundColor Cyan
    try {
        bun add -g opencode-ai
        bun add -g @openai/codex
    } catch {
        Write-Warning "Failed to install Bun tools: $_"
    }
} else {
    Write-Warning "Bun not found. Skipping opencode-ai and codex installation."
}

# Install/update Claude Code (official WinGet package)
Write-Host "Installing/updating Claude Code..." -ForegroundColor Cyan

# Remove bun-installed Claude Code to avoid duplicate claude executables on PATH
if (Get-Command bun -ErrorAction SilentlyContinue) {
    $bunClaude = bun pm ls -g 2>$null | Select-String '@anthropic-ai/claude-code'
    if ($bunClaude) {
        Write-Host "Removing bun-installed @anthropic-ai/claude-code (switching to winget)..." -ForegroundColor Cyan
        try { bun remove -g @anthropic-ai/claude-code } catch { Write-Warning "Failed to remove bun claude-code: $_" }
    }
}

if (-not (Get-Command winget -ErrorAction SilentlyContinue)) {
    Write-Warning 'winget not found. Skipping Claude Code installation.'
} else {
    $claudeInstalled = winget list --id Anthropic.ClaudeCode -e --source winget 2>$null | Select-String -Pattern 'Anthropic\.ClaudeCode'
    if ($claudeInstalled) {
        winget upgrade --id Anthropic.ClaudeCode -e --accept-source-agreements --accept-package-agreements
    } else {
        winget install --id Anthropic.ClaudeCode -e --accept-source-agreements --accept-package-agreements
    }
    if ($LASTEXITCODE -ne 0) {
        Write-Warning "Claude Code installation exited with code $LASTEXITCODE."
    }
}

# ---------- Rust (via rustup) ----------
function Ensure-Rustup {
    if (Get-Command cargo -ErrorAction SilentlyContinue) {
        Write-Host "Rust toolchain already installed ($(cargo --version))." -ForegroundColor DarkGray
        return
    }

    Write-Host 'Installing Rust toolchain via rustup...' -ForegroundColor Cyan
    $installer = Join-Path $env:TEMP 'rustup-init.exe'
    Invoke-WebRequest -Uri 'https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe' -OutFile $installer -UseBasicParsing
    & $installer -y --default-toolchain stable
    Remove-Item $installer -Force -ErrorAction SilentlyContinue

    # Add cargo bin to current session PATH so subsequent steps can find it
    $cargobin = Join-Path $HOME '.cargo\bin'
    if (Test-Path $cargobin) {
        $env:PATH = "$cargobin;$env:PATH"
    }
}

# ---------- Visual Studio Build Tools (via vs_BuildTools.exe) ----------
function Ensure-VsBuildTools {
    $installerDir = Join-Path ${env:ProgramFiles(x86)} 'Microsoft Visual Studio\Installer'
    $vsWhere = Join-Path $installerDir 'vswhere.exe'

    if ((Test-Path $vsWhere) -and (& $vsWhere -products Microsoft.VisualStudio.Product.BuildTools -requires Microsoft.VisualStudio.Workload.VCTools -property installationPath)) {
        Write-Host 'Visual Studio Build Tools (C++) already installed.' -ForegroundColor DarkGray
        return
    }

    $isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
    if (-not $isAdmin) {
        Write-Host 'VS Build Tools requires admin. Elevating...' -ForegroundColor Cyan
        $scriptBlock = @'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
$installer = Join-Path $env:TEMP 'vs_BuildTools.exe'
(New-Object Net.WebClient).DownloadFile('https://aka.ms/vs/17/release/vs_BuildTools.exe', $installer)
& $installer --quiet --wait --norestart --force --includeRecommended `
    --add Microsoft.VisualStudio.Workload.VCTools `
    --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
    --add Microsoft.VisualStudio.Component.Windows11SDK.26100 `
    --add Microsoft.VisualStudio.Component.VC.CMake.Project
Remove-Item $installer -Force -ErrorAction SilentlyContinue
'@
        $encoded = [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($scriptBlock))
        $proc = Start-Process powershell.exe -Verb RunAs -Wait -PassThru -ArgumentList "-NoProfile -EncodedCommand $encoded"
        if ($proc.ExitCode -ne 0 -and $proc.ExitCode -ne 3010) {
            Write-Warning "VS Build Tools installation exited with code $($proc.ExitCode)."
        }
        return
    }

    Write-Host 'Installing Visual Studio Build Tools 2022 (C++ workload)...' -ForegroundColor Cyan
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    $installer = Join-Path $env:TEMP 'vs_BuildTools.exe'
    (New-Object Net.WebClient).DownloadFile('https://aka.ms/vs/17/release/vs_BuildTools.exe', $installer)
    & $installer --quiet --wait --norestart --force --includeRecommended `
        --add Microsoft.VisualStudio.Workload.VCTools `
        --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
        --add Microsoft.VisualStudio.Component.Windows11SDK.26100 `
        --add Microsoft.VisualStudio.Component.VC.CMake.Project
    Remove-Item $installer -Force -ErrorAction SilentlyContinue
}

if ($InstallDevelopmentToolchain) {
    Ensure-Rustup
    Ensure-VsBuildTools
} else {
    Write-Host 'Skipping optional Rust and Visual Studio Build Tools. Use -InstallDevelopmentToolchain to install them.' -ForegroundColor DarkGray
}

# Clean up Scoop rust failed-install residue (frees ~700MB on C: drive)
$rustScoopDir = Join-Path $HOME 'scoop\apps\rust'
if (Test-Path -LiteralPath $rustScoopDir) {
    $rustInfo = scoop export 2>$null | Out-String | ConvertFrom-Json
    $rustApp = $rustInfo.apps | Where-Object { $_.Name -eq 'rust' }
    if ($rustApp -and $rustApp.Info -match 'failed') {
        Write-Host 'Cleaning Scoop rust failed-install residue...' -ForegroundColor Cyan
        scoop uninstall rust 2>$null
        Remove-Item -LiteralPath $rustScoopDir -Recurse -Force -ErrorAction SilentlyContinue
    }
}

# Detect Program Files Neovim shadowing Scoop version (Scoop has 0.11.6, Program Files may have older)
$programFilesNvim = Join-Path $env:ProgramFiles 'Neovim\bin\nvim.exe'
if (Test-Path -LiteralPath $programFilesNvim) {
    $scoopNvimShim = Join-Path $HOME 'scoop\shims\nvim.exe'
    $scoopNvimWin = Test-Path -LiteralPath $scoopNvimShim
    $currentNvim = (Get-Command nvim -ErrorAction SilentlyContinue).Source
    if ($scoopNvimWin -and $currentNvim -and $currentNvim -notlike "$HOME\scoop\*") {
        Write-Warning "Neovim is shadowed: PATH resolves to '$currentNvim' but Scoop has a newer version."
        Write-Warning "Uninstall Program Files Neovim ($env:ProgramFiles\Neovim) so the Scoop shim takes effect."
    }
}

$profileSource = Join-Path $RepoRoot 'powershell\Microsoft.PowerShell_profile.ps1'
$weztermSource = Join-Path $RepoRoot 'wezterm'
$nvimSource = Join-Path $RepoRoot 'nvim'
$yaziSource = Join-Path $RepoRoot 'yazi\config'
$zellijSource = Join-Path $RepoRoot 'zellij\config.kdl'
$claudeSettingsSource = Join-Path $RepoRoot 'claude\settings.json'
$claudeStatuslineSource = Join-Path $RepoRoot 'claude\statusline-command.sh'
$omnirouteEnvExample = Join-Path $RepoRoot 'omniroute\.env.example'

$profileTarget5 = Join-Path $HOME 'Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'
$profileTarget7 = Join-Path $HOME 'Documents\PowerShell\Microsoft.PowerShell_profile.ps1'
$weztermTarget = Join-Path $HOME '.config\wezterm'
$legacyWeztermHome = Join-Path $HOME '.wezterm.lua'
$nvimTarget = Join-Path $env:LOCALAPPDATA 'nvim'
$yaziTarget = Join-Path $env:APPDATA 'yazi\config'
$zellijTarget = Join-Path $env:APPDATA 'Zellij\config\config.kdl'
$claudeDir = Join-Path $HOME '.claude'
$claudeSettingsTarget = Join-Path $claudeDir 'settings.json'
$claudeStatuslineTarget = Join-Path $claudeDir 'statusline-command.sh'
$omnirouteDir = Join-Path $HOME '.omniroute'
$omnirouteEnvTarget = Join-Path $omnirouteDir '.env'

New-Item -ItemType Directory -Force -Path (Split-Path $profileTarget5 -Parent) | Out-Null
New-Item -ItemType Directory -Force -Path (Split-Path $profileTarget7 -Parent) | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $HOME '.config') | Out-Null
New-Item -ItemType Directory -Force -Path (Split-Path $yaziTarget -Parent) | Out-Null
New-Item -ItemType Directory -Force -Path (Split-Path $zellijTarget -Parent) | Out-Null
New-Item -ItemType Directory -Force -Path $claudeDir | Out-Null
New-Item -ItemType Directory -Force -Path $omnirouteDir | Out-Null

New-ProfileLink -LinkPath $profileTarget5 -TargetPath $profileSource
New-ProfileLink -LinkPath $profileTarget7 -TargetPath $profileSource
Remove-LegacyWezTermHomeConfig -LegacyPath $legacyWeztermHome -RepoWezTermDir $weztermSource
New-DirectoryLink -LinkPath $weztermTarget -TargetPath $weztermSource
New-DirectoryLink -LinkPath $nvimTarget -TargetPath $nvimSource
New-DirectoryLink -LinkPath $yaziTarget -TargetPath $yaziSource
New-ZellijConfigLink -LinkPath $zellijTarget -TargetPath $zellijSource
New-ConfigFileLink -LinkPath $claudeSettingsTarget -TargetPath $claudeSettingsSource
New-ConfigFileLink -LinkPath $claudeStatuslineTarget -TargetPath $claudeStatuslineSource

# OmniRoute: seed .env only when missing (never overwrite local secrets)
if (-not (Test-Path -LiteralPath $omnirouteEnvTarget)) {
    Copy-Item -LiteralPath $omnirouteEnvExample -Destination $omnirouteEnvTarget
    Write-Host "Created $omnirouteEnvTarget from example — fill STORAGE_ENCRYPTION_KEY before first OmniRoute start." -ForegroundColor Yellow
} else {
    Write-Host "Keeping existing OmniRoute env: $omnirouteEnvTarget" -ForegroundColor DarkGray
}

if (Get-Command npm -ErrorAction SilentlyContinue) {
    $omniroutePkg = npm list -g omniroute --depth=0 2>$null
    if ($LASTEXITCODE -ne 0) {
        Write-Host 'Installing omniroute globally via npm...' -ForegroundColor Cyan
        npm install -g omniroute
    } else {
        Write-Host 'OmniRoute already installed globally.' -ForegroundColor DarkGray
    }
} else {
    Write-Warning 'npm not found. Skip omniroute install; see omniroute/README.md'
}

# Pre-install Neovim plugins so the first launch is ready (requires GitHub access)
if (Get-Command nvim -ErrorAction SilentlyContinue) {
    Write-Host 'Syncing Neovim plugins (may take a few minutes on first run)...' -ForegroundColor Cyan
    try {
        $nvimProc = Start-Process nvim -ArgumentList '--headless', '"+Lazy! sync"', '+qa' -NoNewWindow -Wait -PassThru
        if ($nvimProc.ExitCode -ne 0) {
            Write-Warning "Neovim plugin sync exited with code $($nvimProc.ExitCode). Open nvim and run :Lazy sync to retry."
        }
    } catch {
        Write-Warning "Neovim plugin sync failed: $_. Open nvim and run :Lazy sync to retry."
    }
}

Write-Host 'pwsh-config bootstrap complete.' -ForegroundColor Green
Write-Host 'Restart PowerShell to load the migrated profile.' -ForegroundColor DarkGray
